accepted = [
    "Apache-2.0",
    "GPL-3.0-only",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
]
targets = [
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
